services:
  it-tools:
    image: "corentinth/it-tools:latest"
    container_name: it-tools
    hostname: it-tools
    restart: always
    env_file:
      - stack.env
    networks:
      - docker-default
    ports:
      - "8587:80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      retries: 3
      timeout: 5s
    labels:
      - "dns_name="

networks:
  docker-default:
    name: docker-default
    external: true
