import os
import sys
import subprocess
import glob
import shutil
from datetime import datetime, timezone

def run_command(command, cwd=None):
    """Executes a shell command and returns the result."""
    print(f"Executing: {' '.join(command)}")
    try:
        return subprocess.run(
            command, cwd=cwd, check=True, 
            capture_output=True, text=True, encoding='utf-8'
        )
    except subprocess.CalledProcessError as e:
        print(f"Error: {e.stderr}", file=sys.stderr)
        sys.exit(1)

def main():
    # --- 1. Configuration ---
    # Note: These point to the artifacts generated by manifest_generator
    source_dir = os.environ.get("DOC_SOURCE_DIR", "deployments/documentation")
    repo_url = os.environ.get("DOCS_REPO_URL")
    token = os.environ.get("CI_GITLAB_TOKEN_GLOBAL_FESER")
    project_name = os.environ.get("CI_PROJECT_NAME", "unknown-service")
    server_host = os.environ.get("CI_SERVER_HOST", "gitlab.int.fam-feser.de")

    if not repo_url or not token:
        print("Fatal: DOCS_REPO_URL or CI_GITLAB_TOKEN_GLOBAL_FESER not set.")
        sys.exit(1)

    auth_url = repo_url.replace("https://", f"https://gitlab-ci-token:{token}@")
    repo_dir = 'docs_repo'

    # --- 2. Find Source Files ---
    source_files = glob.glob(os.path.join(source_dir, '*.md'))
    if not source_files:
        print(f"No Markdown files found in {source_dir}. Skipping.")
        sys.exit(0)

    # --- 3. Setup and Clone ---
    if os.path.exists(repo_dir):
        shutil.rmtree(repo_dir)
        
    run_command(["git", "config", "--global", "user.email", f"ci-bot@{server_host}"])
    run_command(["git", "config", "--global", "user.name", "GitLab CI Documentation Bot"])
    
    # Use a shallow clone for speed
    run_command(["git", "clone", "--depth", "1", auth_url, repo_dir])

    # --- 4. Process Content ---
    # Target: docs_repo/content/aac-services/<project_name>/
    target_dir = os.path.join(repo_dir, 'content', 'aac-services', project_name)
    os.makedirs(target_dir, exist_ok=True)
    
    for src in source_files:
        filename = os.path.basename(src)
        title = os.path.splitext(filename)[0].replace('_', ' ').title()
        dest = os.path.join(target_dir, filename)
        
        now = datetime.now(timezone.utc).isoformat()
        header = (
            "---\n"
            f'title: "{project_name}: {title}"\n'
            f"date: {now}\n"
            f"lastmod: {now}\n"
            "draft: false\n"
            f'description: "Auto-generated documentation for {project_name}"\n'
            "---\n\n"
        )
        
        with open(src, 'r') as f_in:
            content = f_in.read()
        with open(dest, 'w') as f_out:
            f_out.write(header + content)

    # --- 5. Commit and Push with Retry Logic ---
    run_command(["git", "add", "."], cwd=repo_dir)
    
    status = run_command(["git", "status", "--porcelain"], cwd=repo_dir)
    if not status.stdout.strip():
        print("No changes detected in documentation.")
        return

    run_command(["git", "commit", "-m", f"docs: update for {project_name}"], cwd=repo_dir)
    
    # Simple retry loop for concurrent pushes
    for i in range(3):
        try:
            run_command(["git", "push"], cwd=repo_dir)
            print("Successfully published documentation!")
            break
        except:
            print(f"Push failed (attempt {i+1}/3), retrying...")
            run_command(["git", "pull", "--rebase"], cwd=repo_dir)

if __name__ == "__main__":
    main()